# Basic Options
title: Rink Watch
author: Rehma Ashraf
email: 12r.ashraf@gmail.com
description: This is description.
twitter_username: rehmarb
github_username: rehma


# Build Settings
markdown: kramdown
theme: Architect
